
# https://github.com/casey/just

default:
    @just --list

run day='01' part='0' useExample='0':
    roc dev -- {{day}} {{part}} {{useExample}}


get day='01':
    aoc download -o --day {{day}} \
        --input-file ./D{{day}}/in \
        --year 2023