
# https://github.com/casey/just

default:
    @just --list

run day='01' part='1' useExample='0':
    roc run -- {{day}} {{part}} {{useExample}}


get day='01':
    aoc download -o --day {{day}} -I -i ./app/Day{{day}}/in